spring:
  application.name: Lab06 Tool Calling
  main.web-application-type: none     # Do not start a web server.
  ai:
    model.chat: none            # Disable all chat models by default. Models will be explicitly enabled below.
    retry:
      max-attempts: 1           # Maximum number of retry attempts.
      on-client-errors: false   # If false, throw a NonTransientAiException, and do not attempt retry for 4xx client error codes.

  # TODO-03: Adjust the settings below based on the chat model you plan to use.
  # If you plan to use Amazon Bedrock: 
  #   - Scroll down to the 'aws' section to add these settings.
  #   - Set the spring.application.name to "Lab06 Bedrock Tool Calling" or something similar.
  #   - Set spring.ai.model.chat to bedrock-converse to tell SpringAI which autoconfigure class to use.
  #   - Set spring.ai.bedrock.aws.region to "us-west-2", or whichever region you have enabled the model in.
  #   - Set spring.ai.bedrock.converse.chat.options.model to "amazon.nova-micro-v1:0" or equivalent (make sure it is enabled)
  #
  # If you plan to use OpenAI:
  #   - Scroll down to the 'openai' section to add these settings.
  #   - Set the spring.application.name to "Lab06 OpenAI Tool Calling" or something similar.
  #   - Set spring.ai.model.chat to openai to tell SpringAI which autoconfigure class to use.
  #   - Adjust the spring.ai.openai.chat.options.model setting if needed.
  #
  # If you plan to use Azure OpenAI:
  #   - Scroll down to the 'azure' section to add these settings.
  #   - Set the spring.application.name to "Lab06 Azure OpenAI Tool Calling" or something similar.
  #   - Set spring.ai.model.chat to azure-openai to tell SpringAI which autoconfigure class to use.
  #   - Set the spring.ai.azure.openai.endpoint to the value you established during Azure setup.
  #   - Set the spring.ai.azure.openai.chat.options.deployment-name to the value you establised during setup.
  #   - Set the spring.ai.azure.openai.chat.options.model to "gpt-35-turbo" to use the GPT-3.5 model.

---
spring:
  config.activate.on-profile: aws

  ai:
    model.chat: TODO

---
spring:
  config.activate.on-profile: openai

  ai:
    model.chat: TODO

---
spring:
  config.activate.on-profile: azure

  ai:
    model.chat: TODO
