spring:
  application.name: Lab04 Chat Client Features
  main.web-application-type: none     # Do not start a web server.

  ai:
    retry:
      max-attempts: 1           # Maximum number of retry attempts.
    model.chat: none            # Disable all chat models by default. Models will be explicitly enabled below.

    # TODO-01: Adjust the settings below based on the chat model you plan to use.
    # If you plan to use Amazon Bedrock: 
    #   - Set spring.ai.model.chat to bedrock-converse to tell SpringAI which autoconfigure class to use.
    #   - Adjust the region setting if needed.
    #   - Adjust the spring.ai.bedrock.converse.chat.options.model setting if needed.
    # If you plan to use Azure OpenAI:
    #   - Set spring.ai.model.chat to azure-openai to tell SpringAI which autoconfigure class to use.
    #   - Adjust the endpoint and deployment-name settings as needed.
    #   - Adjust the spring.ai.azure.openai.chat.options.model setting if needed.
    # If you plan to use OpenAI:
    #   - Set spring.ai.model.chat to openai to tell SpringAI which autoconfigure class to use.
    #   - Adjust the spring.ai.openai.chat.options.model setting if needed.
    # If you plan to use Ollama:
    #   - Set spring.ai.model.chat to ollama to tell SpringAI which autoconfigure class to use.
    #   - Adjust the base-url and model settings if needed.


---
spring:
  config.activate.on-profile: aws

  application.name: Lab04 Chat Client Features - Bedrock
  ai:
    model.chat: bedrock-converse
    bedrock:
      aws:
        region: us-west-2 # Adjust as needed.
        access-key: NEVER-PLACE-SECRET-KEY-IN-CONFIG-FILE
        secret-key: NEVER-PLACE-SECRET-KEY-IN-CONFIG-FILE
      converse:
        chat:
          options:
            model: anthropic.claude-3-5-sonnet-20240620-v1:0  # Adjust as needed

---
spring:
  config.activate.on-profile: openai

  application.name: Lab04 Chat Client Features - OpenAI
  ai:
    model.chat: openai
    openai:
      api-key: NEVER-PLACE-SECRET-KEY-IN-CONFIG-FILE

---
spring:
  config.activate.on-profile: azure

  application.name: Lab04 Chat Client Features - Azure OpenAI
  ai:
    model.chat: azure-openai
    azure:
      openai:
        api_key: NEVER-PLACE-SECRET-KEY-IN-CONFIG-FILE
        endpoint: ENDPOINT-GOES-HERE                      # Adjust as needed.
        chat:
          options:
            deployment-name: DEPLOYMENT-NAME-GOES-HERE    # Adjust as needed.
            model: gpt-35-turbo                           # Adjust as needed.

---
spring:
  config.activate.on-profile: ollama

  application.name: Lab04 Chat Client Features - Ollama
  ai:
    model.chat: ollama
    ollama:
      base-url: http://localhost:11434  # Adjust as needed.
      chat:
        options:
          model: llama2  # Adjust as needed.

