spring:
  application.name: Lab06 Local Functions
  main.web-application-type: none     # Do not start a web server.
  ai:
    model.chat: none            # Disable all chat models by default. Models will be explicitly enabled below.
    retry:
      max-attempts: 1           # Maximum number of retry attempts.
      on-client-errors: false   # If false, throw a NonTransientAiException, and do not attempt retry for 4xx client error codes.


---
spring:
  config.activate.on-profile: openai

  # TODO-04: Set the spring.application.name to "Lab06 OpenAI Functions" or something similar.
  # Set spring.ai.model.chat to openai to tell SpringAI which autoconfigure class to use.

  application.name: Lab06 OpenAI Functions
  ai:
    model.chat: openai
    openai:
      api-key: NEVER-PLACE-SECRET-KEY-IN-CONFIG-FILE

---
spring:
  config.activate.on-profile: azure

  # TODO-04: Set the spring.application.name to "Lab06 Azure OpenAI Functions" or something similar.
  # Set the spring.ai.azure.openai.endpoint to the value you established during Azure setup.
  # Set the spring.ai.azure.openai.chat.options.deployment-name to the value you establised during setup.
  # Set the spring.ai.azure.openai.chat.options.model to "gpt-35-turbo" to use the GPT-3.5 model.
  # Set spring.ai.model.chat to azure-openai to tell SpringAI which autoconfigure class to use.

  application.name: Lab06 Azure OpenAI Chat
  ai:
    model.chat: azure-openai
    azure:
      openai:
        api_key: NEVER-PLACE-SECRET-KEY-IN-CONFIG-FILE
        endpoint: ENDPOINT-GOES-HERE
        chat:
          options:
            deployment-name: DEPLOYMENT-NAME-GOES-HERE
            model: gpt-35-turbo


