spring:
  application.name: spring.ai
  main.web-application-type: none     # Do not start a web server.

  ai:
    retry:
      max-attempts: 1           # Maximum number of retry attempts.
    openai:
      api-key: key